# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expe	cted to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Squad Wipe
email: timmakesthings@gmail.com
description: Instant gaming articles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: mrtrwhite
github_username:  mrtrwhite
permalink: /:title

# Build settings
markdown: kramdown
